#database name, username and password should not exceed 128 characters
py_auth#!#database|-|11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
py_auth#!#database|-|111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111112
py_auth#!#user|-|11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
py_auth#!#user|-|111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111112
#not sure why any password is accepted during authentication through cloud desktop
#This test should throw error but from cloud desktop a connection is successfully established
#py_auth#!#password|-|11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
py_auth#!#password|-|111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111112
py_auth#!#others|-|packetSize=0
py_auth#!#others|-|packetSize=-1
py_auth#!#others|-|packetSize=4096
py_auth#!#database|-|test1 SELECT 1