#database name, username and password should not exceed 128 characters
py_auth#!#database|-|11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
~~ERROR (Code: 911)~~
~~ERROR (Message: [08004] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]database "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111" does not exist (911) (SQLDriverConnect))~~

py_auth#!#database|-|111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111112
~~ERROR (Code: 0)~~
~~ERROR (Message: [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid value specified for connection string attribute 'DATABASE' (0) (SQLDriverConnect))~~

py_auth#!#user|-|11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
~~ERROR (Code: 18456)~~
~~ERROR (Message: [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111" (18456) (SQLDriverConnect))~~

py_auth#!#user|-|111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111112
~~ERROR (Code: 0)~~
~~ERROR (Message: [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid value specified for connection string attribute 'UID' (0) (SQLDriverConnect))~~

#not sure why any password is accepted during authentication through cloud desktop
#This test should throw error but from cloud desktop a connection is successfully established
#py_auth#!#password|-|11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
py_auth#!#password|-|111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111112
~~ERROR (Code: 0)~~
~~ERROR (Message: [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid value specified for connection string attribute 'PWD' (0) (SQLDriverConnect))~~

py_auth#!#others|-|packetSize=0
~~SUCCESS~~
py_auth#!#others|-|packetSize=-1
~~SUCCESS~~
py_auth#!#others|-|packetSize=4096
~~SUCCESS~~
py_auth#!#database|-|test1 SELECT 1
~~ERROR (Code: 911)~~
~~ERROR (Message: [08004] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]database "test1 select 1" does not exist (911) (SQLDriverConnect))~~


CREATE DATABASE ["龙漫远龍漫😃😄漫遠.¢£€¥"]
py_auth#!#database|-|"龙漫远龍漫😃😄漫遠.¢£€¥"
~~SUCCESS~~
DROP DATABASE ["龙漫远龍漫😃😄漫遠.¢£€¥"]
